baseURL = 'https://ronsblog.ronveen-0b6.workers.dev/'
languageCode = 'en-us'
title = "Ron's Tech Blog"
theme = 'PaperMod'

[params]
    showCodeCopyButtons = true # Allows readers to copy your Java code easily
    disableSpecial1stPost = true # Make first list item same as others (shows thumbnail)
    ShowPostNavLinks = true      # show next/prev post links
    ShowBreadCrumbs = true       # show breadcrumbs on posts

[taxonomies]
  series = "series"
    # Set to true to replace list summary with reading time (e.g., "3 min read")
    listReplaceSummaryWithReadingTime = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[menu]
  [[menu.main]]
    identifier = "articles"
    name = "Articles"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "series"
    name = "Series"
    url = "/series/"
    weight = 12
  [[menu.main]]
    identifier = "shorts"
    name = "Shorts"
    url = "/shorts/"
    weight = 15
  [[menu.main]]
    identifier = "books"
    name = "Books"
    url = "/books/"
    weight = 20
  [[menu.main]]
    identifier = "Conferences"
    name = "Conferences"
    url = "/conferences/"
    weight = 23
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 25
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      attribute = true
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "monokai" # High-contrast style great for Java
